# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SfA4h_px-iVhsCRKuMJp7c0-rOdIglb8
"""

!pip install -q -U langgraph langchain langchain-openai langsmith pydantic

import os

from typing import Literal
from pydantic import BaseModel, Field

from langchain_openai import ChatOpenAI

from langgraph.func import task, entrypoint
from langgraph.checkpoint.memory import MemorySaver
from langgraph.types import interrupt, Command, RetryPolicy

os.environ["OPENAI_API_KEY"] ="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"

from langchain_openai import ChatOpenAI

llm = ChatOpenAI(
    model="openai/gpt-oss-20b:free",
    base_url="https://openrouter.ai/api/v1",
    api_key=os.environ["OPENAI_API_KEY"],
    temperature=0
)

print(llm)

response = llm.invoke("Reply with exactly this word: HELLO")

print(response.content)

from typing import Literal
from pydantic import BaseModel, Field

class TicketClassification(BaseModel):
    """Structured ticket classification."""

    category: Literal["billing", "technical", "human"] = Field(
        description="Ticket category"
    )

    urgency: Literal["low", "medium", "high"] = Field(
        description="Urgency level"
    )

    reason: str = Field(
        description="Reason for the classification"
    )

classifier = llm.with_structured_output(TicketClassification)

def classify_ticket(message: str):
    prompt = f"""
You are a customer support supervisor.

Classify the following customer ticket.

Ticket:
{message}
"""

    return classifier.invoke(prompt)

ticket = classify_ticket(
    "I paid twice and need a refund immediately."
)

print(ticket)

checkpointer = MemorySaver()

@task
def billing_agent(message: str):

    return {
        "agent": "Billing Agent",
        "response": f"Billing request received: {message}"
    }

@task
def technical_agent(message: str):

    return {
        "agent": "Technical Agent",
        "response": f"Technical support request received: {message}"
    }

@task
def human_agent(message: str):

    approval = interrupt(
        {
            "message": message,
            "question": "Approve human support?"
        }
    )

    return {
        "agent": "Human Agent",
        "approval": approval
    }

@task
def supervisor(message: str):

    ticket = classify_ticket(message)

    return ticket

@entrypoint(checkpointer=checkpointer)
def customer_support_workflow(input_data: dict):

    customer_id = input_data["customer_id"]
    message = input_data["message"]

    save_customer_memory(
        customer_id,
        message
    ).result()

    ticket = safe_classification(message).result()


    if ticket.category == "billing":

        return billing_agent(message).result()


    elif ticket.category == "technical":

        return technical_agent(message).result()


    else:

        return human_agent(message).result()

config = {
    "configurable": {
        "thread_id": "thread-1"
    }
}

result = customer_support_workflow.invoke(
    {
        "customer_id": "customer-001",
        "message": "I paid twice and need a refund."
    },
    config=config
)

print(result)

customer_store = {}

@task
def save_customer_memory(customer_id: str, message: str):

    history = customer_store.get(customer_id, [])

    history.append(message)

    customer_store[customer_id] = history

    return history

@entrypoint(checkpointer=checkpointer)
def customer_support_workflow(input_data: dict):

    customer_id = input_data["customer_id"]
    message = input_data["message"]

    # long term memory
    save_customer_memory(
        customer_id,
        message
    ).result()

    # LLM supervisor
    ticket = safe_classification(message).result()


    if ticket.category == "billing":

        return billing_agent(message).result()


    elif ticket.category == "technical":

        return technical_agent(message).result()


    else:

        return human_agent(message).result()

config = {
    "configurable": {
        "thread_id": "billing-test"
    }
}


result = customer_support_workflow.invoke(
    {
        "customer_id":"customer-001",
        "message":"I paid twice and need a refund immediately."
    },
    config=config
)


print(result)

@entrypoint(checkpointer=checkpointer)
def customer_support_workflow(customer_id: str, message: str):

    save_customer_memory(customer_id, message).result()

    ticket = supervisor(message).result()

    if ticket.category == "billing":
        return billing_agent(message).result()

    elif ticket.category == "technical":
        return technical_agent(message).result()

    else:
        return human_agent(message).result()

@task(
    retry_policy=RetryPolicy(
        max_attempts=3
    )
)
def safe_classification(message: str):
    return classify_ticket(message)

@entrypoint(checkpointer=checkpointer)
def customer_support_workflow(input_data: dict):

    customer_id = input_data["customer_id"]
    message = input_data["message"]

    save_customer_memory(customer_id, message).result()

    ticket = safe_classification(message).result()

    if ticket.category == "billing":
        return billing_agent(message).result()

    elif ticket.category == "technical":
        return technical_agent(message).result()

    else:
        return human_agent(message).result()

result = customer_support_workflow.invoke(
    {
        "customer_id": "cust-001",
        "message": "I still have the same login problem."
    },
    config=config
)

print(customer_store)

@task
def billing_agent(message: str):

    prompt = f"""
You are a billing support agent.

Customer message:
{message}

Provide a professional response.
"""

    response = llm.invoke(prompt)


    return {
        "agent":"Billing Agent",
        "response":response.content
    }

@task
def technical_agent(message: str):

    prompt = f"""
You are a technical support agent.

Customer message:
{message}

Provide troubleshooting steps.
"""

    response = llm.invoke(prompt)


    return {
        "agent":"Technical Agent",
        "response":response.content
    }

result = customer_support_workflow.invoke(
    {
        "customer_id":"customer-002",
        "message":"My account is locked and I cannot login."
    },
    config={
        "configurable":{
            "thread_id":"technical-test"
        }
    }
)


print(result)

@task(
    retry_policy=RetryPolicy(
        max_attempts=3
    )
)
def safe_classification(message: str):

    result = classify_ticket(message)

    if result is None:
        raise ValueError("Empty classification result")

    return result

config = {
    "configurable": {
        "thread_id": "human-test"
    }
}

result = customer_support_workflow.invoke(
    {
        "customer_id": "customer-003",
        "message": "I am very angry and I want to talk to a human manager."
    },
    config=config
)

print(result)

resume_result = customer_support_workflow.invoke(
    Command(
        resume="Approved, connect customer with human support."
    ),
    config=config
)

print(resume_result)

customer_support_workflow.invoke(
    {
        "customer_id":"customer-memory-test",
        "message":"I have a billing problem."
    },
    config={
        "configurable":{
            "thread_id":"thread-one"
        }
    }
)

customer_support_workflow.invoke(
    {
        "customer_id":"customer-memory-test",
        "message":"I still need help with my previous issue."
    },
    config={
        "configurable":{
            "thread_id":"thread-two"
        }
    }
)

print(customer_store)